#!/bin/bash
JSON_FILE="data.json"

jq -r '.name, .height, .weight, .types[0].type.name' "$JSON_FILE" | \
sed '1s/^./\u&/; 4s/^./\u&/' | \
awk '
{
  if (NR==1) name = $0
  if (NR==2) height = $0
  if (NR==3) weight = $0
  if (NR==4) type = $0
}
END {
  formatted_weight = weight_hg / 10
  formatted_height = height_dm / 10

  printf "%s is of type %s, weighs %skg, and is %sm tall.\n", \
      name, type, formatted_weight, formatted_height
}'
