#!/bin/bash
JSON_FILE="data.json"

jq -r '.name, .height, .weight, .types[0].type.name' "$JSON_FILE" | \
awk '
{
  if (NR==1) name = $0
  if (NR==2) height = $0
  if (NR==3) weight = $0
  if (NR==4) type = $0
}
END {
  name = toupper(substr(name, 1, 1)) substr(name, 2)
  type = toupper(substr(type, 1, 1)) substr(type, 2)

  printf "%s is of type %s, weighs %skg, and is %sm tall.\n", \
      name, type, (weight / 10), (height / 10)
}'
